var synidaemi = {
  'Stærðfræði, neðra þrep': {
    'heiti': 'Stærðfræði, neðra þrep',
    'lagmark': 17,
    'hamark_n': 28,
    'hamark_e': 30,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 20,
    'verkefnisgerd': 8,
    'lokaprof': 12,
    'onnur_vinna': 0,
    'vinna_per_nemanda': 110,
    'fragangur_namsmats': 40,
    'onnur_vinna_per_nemanda': 0,
    'kostn_per_nem_yn': 3,
    'kostn_per_nem_ye': 5
  },
  'Stærðfræði, efra þrep': {
    'heiti': 'Stærðfræði, efra þrep',
    'lagmark': 17,
    'hamark_n': 28,
    'hamark_e': 30,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 20,
    'verkefnisgerd': 8,
    'lokaprof': 12,
    'onnur_vinna': 0,
    'vinna_per_nemanda': 120,
    'fragangur_namsmats': 40,
    'onnur_vinna_per_nemanda': 0,
    'kostn_per_nem_yn': 3.2,
    'kostn_per_nem_ye': 5.3
  },
  'Jarðfræði': {
    'heiti': 'Jarðfræði',
    'lagmark': 17,
    'hamark_n': 28,
    'hamark_e': 30,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 20,
    'verkefnisgerd': 8,
    'lokaprof': 12,
    'onnur_vinna': 0,
    'vinna_per_nemanda': 110,
    'fragangur_namsmats': 40,
    'onnur_vinna_per_nemanda': 0,
    'kostn_per_nem_yn': 3,
    'kostn_per_nem_ye': 5
  },
  'Enska, neðra þrep': {
    'heiti': 'Enska, neðra þrep',
    'lagmark': 17,
    'hamark_n': 28,
    'hamark_e': 30,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 20,
    'verkefnisgerd': 8,
    'lokaprof': 12,
    'onnur_vinna': 4,
    'vinna_per_nemanda': 110,
    'fragangur_namsmats': 40,
    'onnur_vinna_per_nemanda': 0,
    'kostn_per_nem_yn': 3,
    'kostn_per_nem_ye': 5
  },
  'Enska, efra þrep': {
    'heiti': 'Enska, efra þrep',
    'lagmark': 17,
    'hamark_n': 28,
    'hamark_e': 30,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 20,
    'verkefnisgerd': 10,
    'lokaprof': 12,
    'onnur_vinna': 4,
    'vinna_per_nemanda': 120,
    'fragangur_namsmats': 40,
    'onnur_vinna_per_nemanda': 0,
    'kostn_per_nem_yn': 3.2,
    'kostn_per_nem_ye': 5.3
  },
  'Danska, neðra þrep': {
    'heiti': 'Danska, neðra þrep',
    'lagmark': 17,
    'hamark_n': 28,
    'hamark_e': 30,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 20,
    'verkefnisgerd': 8,
    'lokaprof': 12,
    'onnur_vinna': 4,
    'vinna_per_nemanda': 110,
    'fragangur_namsmats': 40,
    'onnur_vinna_per_nemanda': 0,
    'kostn_per_nem_yn': 3,
    'kostn_per_nem_ye': 5
  },
  'Danska, efra þrep': {
    'heiti': 'Danska, efra þrep',
    'lagmark': 17,
    'hamark_n': 28,
    'hamark_e': 30,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 20,
    'verkefnisgerd': 10,
    'lokaprof': 12,
    'onnur_vinna': 4,
    'vinna_per_nemanda': 120,
    'fragangur_namsmats': 40,
    'onnur_vinna_per_nemanda': 0,
    'kostn_per_nem_yn': 3.2,
    'kostn_per_nem_ye': 5.3
  },
  'Erlend mál, neðra þrep': {
    'heiti': 'Erlend mál, neðra þrep',
    'lagmark': 17,
    'hamark_n': 28,
    'hamark_e': 30,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 20,
    'verkefnisgerd': 8,
    'lokaprof': 12,
    'onnur_vinna': 4,
    'vinna_per_nemanda': 110,
    'fragangur_namsmats': 40,
    'onnur_vinna_per_nemanda': 0,
    'kostn_per_nem_yn': 3,
    'kostn_per_nem_ye': 5
  },
  'Erlend mál, efra þrep': {
    'heiti': 'Erlend mál, efra þrep',
    'lagmark': 17,
    'hamark_n': 28,
    'hamark_e': 30,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 20,
    'verkefnisgerd': 10,
    'lokaprof': 12,
    'onnur_vinna': 4,
    'vinna_per_nemanda': 120,
    'fragangur_namsmats': 40,
    'onnur_vinna_per_nemanda': 0,
    'kostn_per_nem_yn': 3.2,
    'kostn_per_nem_ye': 5.3
  },
  'Félagsgreinar, neðra þrep': {
    'heiti': 'Félagsgreinar, neðra þrep',
    'lagmark': 17,
    'hamark_n': 28,
    'hamark_e': 30,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 20,
    'verkefnisgerd': 8,
    'lokaprof': 12,
    'onnur_vinna': 4,
    'vinna_per_nemanda': 110,
    'fragangur_namsmats': 40,
    'onnur_vinna_per_nemanda': 0,
    'kostn_per_nem_yn': 3,
    'kostn_per_nem_ye': 5
  },
  'Félagsgreinar, efra þrep': {
    'heiti': 'Félagsgreinar, efra þrep',
    'lagmark': 17,
    'hamark_n': 28,
    'hamark_e': 30,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 20,
    'verkefnisgerd': 10,
    'lokaprof': 12,
    'onnur_vinna': 4,
    'vinna_per_nemanda': 120,
    'fragangur_namsmats': 40,
    'onnur_vinna_per_nemanda': 0,
    'kostn_per_nem_yn': 3.2,
    'kostn_per_nem_ye': 5.3
  },
  'Almenn braut': {
    'heiti': 'Almenn braut',
    'lagmark': 10,
    'hamark_n': 18,
    'hamark_e': 18,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 15,
    'verkefnisgerd': 8,
    'lokaprof': 12,
    'onnur_vinna': 18.5,
    'vinna_per_nemanda': 90,
    'fragangur_namsmats': 40,
    'onnur_vinna_per_nemanda': 60,
    'kostn_per_nem_yn': 6.3,
    'kostn_per_nem_ye': 6.3
  },
  'Íslenska, hægferð': {
    'heiti': 'Íslenska, hægferð',
    'lagmark': 17,
    'hamark_n': 28,
    'hamark_e': 30,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 15,
    'verkefnisgerd': 8,
    'lokaprof': 12,
    'onnur_vinna': 3.5,
    'vinna_per_nemanda': 110,
    'fragangur_namsmats': 40,
    'onnur_vinna_per_nemanda': 0,
    'kostn_per_nem_yn': 3,
    'kostn_per_nem_ye': 5
  },
  'Stærðfræði, hægferð': {
    'heiti': 'Stærðfræði, hægferð',
    'lagmark': 17,
    'hamark_n': 28,
    'hamark_e': 30,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 15,
    'verkefnisgerd': 8,
    'lokaprof': 12,
    'onnur_vinna': 3.5,
    'vinna_per_nemanda': 110,
    'fragangur_namsmats': 40,
    'onnur_vinna_per_nemanda': 0,
    'kostn_per_nem_yn': 3,
    'kostn_per_nem_ye': 5
  },
  'Danska, hægferð': {
    'heiti': 'Danska, hægferð',
    'lagmark': 17,
    'hamark_n': 28,
    'hamark_e': 30,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 15,
    'verkefnisgerd': 8,
    'lokaprof': 12,
    'onnur_vinna': 3.5,
    'vinna_per_nemanda': 110,
    'fragangur_namsmats': 40,
    'onnur_vinna_per_nemanda': 0,
    'kostn_per_nem_yn': 3,
    'kostn_per_nem_ye': 5
  },
  'Enska, hægferð': {
    'heiti': 'Enska, hægferð',
    'lagmark': 17,
    'hamark_n': 28,
    'hamark_e': 30,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 15,
    'verkefnisgerd': 8,
    'lokaprof': 12,
    'onnur_vinna': 3.5,
    'vinna_per_nemanda': 110,
    'fragangur_namsmats': 40,
    'onnur_vinna_per_nemanda': 0,
    'kostn_per_nem_yn': 3,
    'kostn_per_nem_ye': 5
  },
  'Íslenska, neðra þrep': {
    'heiti': 'Íslenska, neðra þrep',
    'lagmark': 17,
    'hamark_n': 28,
    'hamark_e': 30,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 20,
    'verkefnisgerd': 8,
    'lokaprof': 12,
    'onnur_vinna': 5,
    'vinna_per_nemanda': 120,
    'fragangur_namsmats': 40,
    'onnur_vinna_per_nemanda': 0,
    'kostn_per_nem_yn': 3.2,
    'kostn_per_nem_ye': 5.3
  },
  'Íslenska, efra þrep': {
    'heiti': 'Íslenska, efra þrep',
    'lagmark': 17,
    'hamark_n': 28,
    'hamark_e': 30,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 20,
    'verkefnisgerd': 10,
    'lokaprof': 12,
    'onnur_vinna': 7,
    'vinna_per_nemanda': 120,
    'fragangur_namsmats': 40,
    'onnur_vinna_per_nemanda': 0,
    'kostn_per_nem_yn': 3.2,
    'kostn_per_nem_ye': 5.3
  },
  'Listgreinar, neðra þrep': {
    'heiti': 'Listgreinar, neðra þrep',
    'lagmark': 10,
    'hamark_n': 18,
    'hamark_e': 18,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 20,
    'verkefnisgerd': 20,
    'lokaprof': 0,
    'onnur_vinna': 21,
    'vinna_per_nemanda': 110,
    'fragangur_namsmats': 40,
    'onnur_vinna_per_nemanda': 0,
    'kostn_per_nem_yn': 5,
    'kostn_per_nem_ye': 5
  },
  'Listgreinar, efra þrep': {
    'heiti': 'Listgreinar, efra þrep',
    'lagmark': 10,
    'hamark_n': 18,
    'hamark_e': 18,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 20,
    'verkefnisgerd': 22,
    'lokaprof': 0,
    'onnur_vinna': 18,
    'vinna_per_nemanda': 120,
    'fragangur_namsmats': 40,
    'onnur_vinna_per_nemanda': 0,
    'kostn_per_nem_yn': 5,
    'kostn_per_nem_ye': 5
  },
  'Raungreinar, efra þrep': {
    'heiti': 'Raungreinar, efra þrep',
    'lagmark': 15,
    'hamark_n': 26,
    'hamark_e': 26,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 20,
    'verkefnisgerd': 10,
    'lokaprof': 12,
    'onnur_vinna': 7.5,
    'vinna_per_nemanda': 120,
    'fragangur_namsmats': 40,
    'onnur_vinna_per_nemanda': 0,
    'kostn_per_nem_yn': 5.3,
    'kostn_per_nem_ye': 5.3
  },
  'Raungreinar, neðra þrep': {
    'heiti': 'Raungreinar, neðra þrep',
    'lagmark': 15,
    'hamark_n': 26,
    'hamark_e': 26,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 20,
    'verkefnisgerd': 8,
    'lokaprof': 12,
    'onnur_vinna': 7.5,
    'vinna_per_nemanda': 110,
    'fragangur_namsmats': 40,
    'onnur_vinna_per_nemanda': 0,
    'kostn_per_nem_yn': 5,
    'kostn_per_nem_ye': 5
  },
  'Almennar raungreinar': {
    'heiti': 'Almennar raungreinar',
    'lagmark': 17,
    'hamark_n': 28,
    'hamark_e': 30,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 20,
    'verkefnisgerd': 8,
    'lokaprof': 12,
    'onnur_vinna': 0,
    'vinna_per_nemanda': 110,
    'fragangur_namsmats': 40,
    'onnur_vinna_per_nemanda': 0,
    'kostn_per_nem_yn': 3,
    'kostn_per_nem_ye': 5
  },
  'Sjúkraliðabraut': {
    'heiti': 'Sjúkraliðabraut',
    'lagmark': 17,
    'hamark_n': 28,
    'hamark_e': 30,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 20,
    'verkefnisgerd': 8,
    'lokaprof': 12,
    'onnur_vinna': 4,
    'vinna_per_nemanda': 110,
    'fragangur_namsmats': 40,
    'onnur_vinna_per_nemanda': 0,
    'kostn_per_nem_yn': 3,
    'kostn_per_nem_ye': 5
  },
  'Verklegt': {
    'heiti': 'Verklegt',
    'lagmark': 8,
    'hamark_n': 14,
    'hamark_e': 14,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 20,
    'verkefnisgerd': 8,
    'lokaprof': 12,
    'onnur_vinna': 31.5,
    'vinna_per_nemanda': 95,
    'fragangur_namsmats': 40,
    'onnur_vinna_per_nemanda': 0,
    'kostn_per_nem_yn': 4.5,
    'kostn_per_nem_ye': 4.5
  },
  'Fagbóklegt': {
    'heiti': 'Fagbóklegt',
    'lagmark': 10,
    'hamark_n': 18,
    'hamark_e': 18,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 20,
    'verkefnisgerd': 10,
    'lokaprof': 12,
    'onnur_vinna': 16.5,
    'vinna_per_nemanda': 120,
    'fragangur_namsmats': 40,
    'onnur_vinna_per_nemanda': 0,
    'kostn_per_nem_yn': 5.3,
    'kostn_per_nem_ye': 5.3
  },
  'Tölvuáfangar': {
    'heiti': 'Tölvuáfangar',
    'lagmark': 12,
    'hamark_n': 22,
    'hamark_e': 22,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 20,
    'verkefnisgerd': 10,
    'lokaprof': 10,
    'onnur_vinna': 12,
    'vinna_per_nemanda': 120,
    'fragangur_namsmats': 40,
    'onnur_vinna_per_nemanda': 0,
    'kostn_per_nem_yn': 5.3,
    'kostn_per_nem_ye': 5.3
  },
  'Íþróttafræði': {
    'heiti': 'Íþróttafræði',
    'lagmark': 17,
    'hamark_n': 28,
    'hamark_e': 30,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 20,
    'verkefnisgerd': 8,
    'lokaprof': 12,
    'onnur_vinna': 4.3,
    'vinna_per_nemanda': 90,
    'fragangur_namsmats': 40,
    'onnur_vinna_per_nemanda': 0,
    'kostn_per_nem_yn': 2.6,
    'kostn_per_nem_ye': 4.3
  },
  'Íþróttir': {
    'heiti': 'Íþróttir',
    'lagmark': 17,
    'hamark_n': 28,
    'hamark_e': 30,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 20,
    'verkefnisgerd': 12,
    'lokaprof': 0,
    'onnur_vinna': 6,
    'vinna_per_nemanda': 90,
    'fragangur_namsmats': 60,
    'onnur_vinna_per_nemanda': 0,
    'kostn_per_nem_yn': 3,
    'kostn_per_nem_ye': 5.1
  },
    'Starfsbraut (1/3)': {
    'heiti': 'Starfsbraut (1/3)',
    'lagmark': 1,
    'hamark_n': 3,
    'hamark_e': 3,
    'timar_namsAetlun': 12,
    'undirb_kennslu': 20,
    'verkefnisgerd': 21,
    'lokaprof': 0,
    'onnur_vinna': 54,
    'vinna_per_nemanda': 0,
    'fragangur_namsmats': 75,
    'onnur_vinna_per_nemanda': 120,
    'kostn_per_nem_yn': 0,
    'kostn_per_nem_ye': 0
  },
    'Starfsbraut (4/6)': {
    'heiti': 'Starfsbraut (4/6)',
    'lagmark': 4,
    'hamark_n': 6,
    'hamark_e': 6,
    'timar_namsAetlun': 12,
    'undirb_kennslu': 20,
    'verkefnisgerd': 21,
    'lokaprof': 0,
    'onnur_vinna': 54,
    'vinna_per_nemanda': 0,
    'fragangur_namsmats': 75,
    'onnur_vinna_per_nemanda': 105,
    'kostn_per_nem_yn': 0,
    'kostn_per_nem_ye': 0
  },
    'Starfsbraut (7/12)': {
    'heiti': 'Starfsbraut (7/12)',
    'lagmark': 7,
    'hamark_n': 12,
    'hamark_e': 12,
    'timar_namsAetlun': 12,
    'undirb_kennslu': 20,
    'verkefnisgerd': 21,
    'lokaprof': 0,
    'onnur_vinna': 54,
    'vinna_per_nemanda': 0,
    'fragangur_namsmats': 75,
    'onnur_vinna_per_nemanda': 90,
    'kostn_per_nem_yn': 0,
    'kostn_per_nem_ye': 0
  },
  'Fjarnám': {
    'heiti': 'Fjarnám',
    'lagmark': 0,
    'hamark_n': 0,
    'hamark_e': 0,
    'timar_namsAetlun': 0,
    'undirb_kennslu': 0,
    'verkefnisgerd': 0,
    'lokaprof': 0,
    'onnur_vinna': 0,
    'vinna_per_nemanda': 0,
    'fragangur_namsmats': 0,
    'onnur_vinna_per_nemanda': 0,
    'kostn_per_nem_yn': 0,
    'kostn_per_nem_ye': 0
  },
  'Sýnidæmið mitt': {
    'heiti': 'Sýnidæmið mitt',
    'lagmark': 17,
    'hamark_n': 28,
    'hamark_e': 30,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 20,
    'verkefnisgerd': 8,
    'lokaprof': 12,
    'onnur_vinna': 4,
    'vinna_per_nemanda': 0,
    'fragangur_namsmats': 0,
    'onnur_vinna_per_nemanda': 150,
    'kostn_per_nem_yn': 3,
    'kostn_per_nem_ye': 5
  },
  'Default': {
    'heiti:':"Default",
    'lagmark': 0,
    'hamark_n': 0,
    'hamark_e': 0,
    'timar_namsAetlun': 0,
    'undirb_kennslu': 0,
    'verkefnisgerd': 0,
    'lokaprof': 0,
    'onnur_vinna': 0,
    'vinna_per_nemanda': 0,
    'fragangur_namsmats': 0,
    'onnur_vinna_per_nemanda': 0,
    'kostn_per_nem_yn': 0,
    'kostn_per_nem_ye': 0
  }
};