var synidaemi = {
  'Stærðfræði': {
    'heiti': 'Stærðfræði',
    'lagmark': 17,
    'hamark_n': 28,
    'hamark_e': 30,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 20,
    'verkefnisgerd': 22,
    'onnur_vinna': 3,
    'vinna_per_nemanda': 160,
    'kostn_per_nem_yn': 3.2,
    'kostn_per_nem_ye': 5.3
  },
  'Tungumál': {
    'heiti': 'Tungumál',
    'lagmark': 17,
    'hamark_n': 28,
    'hamark_e': 30,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 20,
    'verkefnisgerd': 22,
    'onnur_vinna': 4,
    'vinna_per_nemanda': 160,
    'kostn_per_nem_yn': 3.2,
    'kostn_per_nem_ye': 5.3
  },
  
  'Félagsgreinar': {
    'heiti': 'Félagsgreinar',
    'lagmark': 17,
    'hamark_n': 28,
    'hamark_e': 30,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 20,
    'verkefnisgerd': 22,
    'onnur_vinna': 4,
    'vinna_per_nemanda': 160,
    'kostn_per_nem_yn': 3.2,
    'kostn_per_nem_ye': 5.3
  },
  'Almenn braut': {
    'heiti': 'Almenn braut',
    'lagmark': 10,
    'hamark_n': 18,
    'hamark_e': 18,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 15,
    'verkefnisgerd': 22,
    'onnur_vinna': 15,
    'vinna_per_nemanda': 200,
    'kostn_per_nem_yn': 6.7,
    'kostn_per_nem_ye': 6.7
  },
  'Hægferð': {
    'heiti': 'Hægferð',
    'lagmark': 17,
    'hamark_n': 28,
    'hamark_e': 30,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 15,
    'verkefnisgerd': 22,
    'onnur_vinna': 3,
    'vinna_per_nemanda': 160,
    'kostn_per_nem_yn': 3.2,
    'kostn_per_nem_ye': 5.3
  },
  'Íslenska': {
    'heiti': 'Íslenska',
    'lagmark': 17,
    'hamark_n': 28,
    'hamark_e': 30,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 20,
    'verkefnisgerd': 22,
    'onnur_vinna': 7,
    'vinna_per_nemanda': 160,
    'kostn_per_nem_yn': 3.2,
    'kostn_per_nem_ye': 5.3
  },
  'Listgreinar': {
    'heiti': 'Listgreinar',
    'lagmark': 10,
    'hamark_n': 18,
    'hamark_e': 18,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 20,
    'verkefnisgerd': 22,
    'onnur_vinna': 18,
    'vinna_per_nemanda': 160,
    'kostn_per_nem_yn': 5.3,
    'kostn_per_nem_ye': 5.3
  },
  'Raungreinar': {
    'heiti': 'Raungreinar',
    'lagmark': 15,
    'hamark_n': 26,
    'hamark_e': 26,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 20,
    'verkefnisgerd': 22,
    'onnur_vinna': 7.5,
    'vinna_per_nemanda': 160,
    'kostn_per_nem_yn': 5.3,
    'kostn_per_nem_ye': 5.3
  },
  'Verklegt': {
    'heiti': 'Verklegt',
    'lagmark': 8,
    'hamark_n': 14,
    'hamark_e': 14,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 20,
    'verkefnisgerd': 22,
    'onnur_vinna': 30,
    'vinna_per_nemanda': 150,
    'kostn_per_nem_yn': 5.0,
    'kostn_per_nem_ye': 5.0
  },
  'Fagbóklegt': {
    'heiti': 'Fagbóklegt',
    'lagmark': 10,
    'hamark_n': 18,
    'hamark_e': 18,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 20,
    'verkefnisgerd': 22,
    'onnur_vinna': 16.5,
    'vinna_per_nemanda': 160,
    'kostn_per_nem_yn': 5.3,
    'kostn_per_nem_ye': 5.3
  },
  'Tölvuáfangar': {
    'heiti': 'Tölvuáfangar',
    'lagmark': 12,
    'hamark_n': 22,
    'hamark_e': 22,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 20,
    'verkefnisgerd': 22,
    'onnur_vinna': 12,
    'vinna_per_nemanda': 160,
    'kostn_per_nem_yn': 5.3,
    'kostn_per_nem_ye': 5.3
  },
  'Íþróttafræði': {
    'heiti': 'Íþróttafræði',
    'lagmark': 17,
    'hamark_n': 28,
    'hamark_e': 30,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 20,
    'verkefnisgerd': 22,
    'onnur_vinna': 0,
    'vinna_per_nemanda': 140,
    'kostn_per_nem_yn': 2.8,
    'kostn_per_nem_ye': 4.7
  },
  'Íþróttir': {
    'heiti': 'Íþróttir',
    'lagmark': 17,
    'hamark_n': 28,
    'hamark_e': 30,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 20,
    'verkefnisgerd': 14.1,
    'onnur_vinna': 6,
    'vinna_per_nemanda': 159,
    'kostn_per_nem_yn': 3.3,
    'kostn_per_nem_ye': 5.4
  },
    'Starfsbraut (1/3)': {
    'heiti': 'Starfsbraut (1/3)',
    'lagmark': 1,
    'hamark_n': 3,
    'hamark_e': 3,
    'timar_namsAetlun': 12,
    'undirb_kennslu': 20,
    'verkefnisgerd': 21,
    'onnur_vinna': 54,
    'vinna_per_nemanda': 195,
    'kostn_per_nem_yn': 0,
    'kostn_per_nem_ye': 0
  },
    'Starfsbraut (4/6)': {
    'heiti': 'Starfsbraut (4/6)',
    'lagmark': 4,
    'hamark_n': 6,
    'hamark_e': 6,
    'timar_namsAetlun': 12,
    'undirb_kennslu': 20,
    'verkefnisgerd': 21,
    'onnur_vinna': 54,
    'vinna_per_nemanda': 180,
    'kostn_per_nem_yn': 0,
    'kostn_per_nem_ye': 0
  },
    'Starfsbraut (7/12)': {
    'heiti': 'Starfsbraut (7/12)',
    'lagmark': 7,
    'hamark_n': 12,
    'hamark_e': 12,
    'timar_namsAetlun': 12,
    'undirb_kennslu': 20,
    'verkefnisgerd': 21,
    'onnur_vinna': 54,
    'vinna_per_nemanda': 165,
    'kostn_per_nem_yn': 0,
    'kostn_per_nem_ye': 0
  },
  'Sýnidæmið mitt': {
    'heiti': 'Sýnidæmið mitt',
    'lagmark': 17,
    'hamark_n': 28,
    'hamark_e': 30,
    'timar_namsAetlun': 6,
    'undirb_kennslu': 20,
    'verkefnisgerd': 20,
    'onnur_vinna': 4,
    'vinna_per_nemanda': 160,
    'kostn_per_nem_yn': 3,
    'kostn_per_nem_ye': 5
  }
};